config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :movies do
    collection do
      get 'search'
    end
  	resources :reviews, except: [:show, :index] do 
  			post 'movie/:id/review/create ', to: "reviews#create"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	searchkick
	belongs_to :user
	has_many :reviews

	has_attached_file :image, styles: { medium: "400x600#{}>"}
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!, except: [:index, :show]
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search]) 
    else
      @movie = Movie.all
    end
  end
  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  before_action :set_movie

  # GET /reviews
  # GET /reviews.json

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = params[:movie_id]
    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_path(params[:movie_id]), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(update_params)
        format.html { redirect_to movie_path(params[:movie_id]), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Review was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find_by_id(params[:id])
    end
    def set_movie
      @movie =  Movie.find_by_id(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.permit(:rating, :comment, :movie_id)
    end
     def update_params
      @a=params[:review]
      b=@a.merge(review_params)
      b.permit(:rating, :comment, :movie_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class= "navbar navbar-default" role="navigation">
	
		<!-- Collect the nav links, forms =, and other content for toggling -->
		<div class ="w">
		<div class="topnav" id="bs-example-navbar-collapse-1">
			<ul style="list-style: none; width: 1170px">
				<li><button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button></li>
				<li><%= link_to "Movie Reviews", root_path, class: "active" %></li>
				<% if user_signed_in? %>
					<li><%= link_to "New Movie",new_movie_path %></li>
					<li><%= link_to "Account",edit_user_registration_path %></li>
				<% else %>
 					<li><%- link_to "sign_up", new_user_session_path %></li>
				<% end %>
        <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "search", name: nil, class: "btn btn-default" %>
        </p>
        <% end %>
			</ul>
		</div>
	</div>
</nav>

<style>

li {
  float: left;
}
li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}
li a:hover {
  background-color: #111;
}
* {box-sizing: border-box;}
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav li {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav .search-container {
  float: right;
  display: flex;
  width: 20%;
}
}

.topnav input[type=text] {
  padding: 6px;
  margin-top: 8px;
  font-size: 17px;
  border: none;
}

.topnav .search-container button {
  float: right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 16px;
  background: #ddd;
  font-size: 17px;
  border: none;
  cursor: pointer;
}

.topnav .search-container button:hover {
  background: #ccc;
}

@media screen and (max-width: 600px) {
  .topnav .search-container {
    float: none;
  }
  .topnav a, .topnav input[type=text], .topnav .search-container button {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  .topnav input[type=text] {
    border: 1px solid #ccc;  
  }
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <%= render 'layouts/header' %>
        <% flash.each do |name,msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <%end%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true,html: { multipart: true }) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :movie_length %>
    <%= form.text_field :movie_length %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style type="text/css">
  nav.navbar.navbar-default {
    padding: 0;
    margin-bottom: 10px;
}
nav.navbar.navbar-default .container{
  padding: 0;
}
.topnav{
  width: 100%;
}
</style>
<% if !user_signed_in? %>
  <div class="jumbotron">
    <head> hahahaha your movies are reviewed here!!!!!</head>
    <%= link_to "sign up to write a review", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <% end -%>
  </div>
<div class = "row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium) , class: "image", width: "100%"), movie %>
      </div>
    </div>
  <% end %>
</div>




<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<div class = "row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium) , class: "image", width: "100%"), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class = "pannel pannel-default">
    <div class= "pannel-body">
      <div class= "row">
        <div class="col-md-5">
          <%= image_tag @movie.image.url(:medium) %>
          <div class="table-resposible">
            <table class = " table" >
              <tbody>
                <tr>
                  <td><strong>Title: <%= @movie.title %></strong></td>
                </tr>
                <tr>
                  <td><strong>Description:</strong>
                      <%= @movie.description %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong>Movie length:</strong>
                    <%= @movie.movie_length %>
                  </td>
                </tr>
                <tr>
                  <td>
                     <strong>Director:</strong>
                      <%= @movie.director %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong>Rating:</strong>
                    <%= @movie.rating %>
                  </td>
                </tr>
              </tbody>
            </table>
            <%= link_to "write a movie review",  new_movie_review_path(@movie.id) %>
          </div>
        </div>
        <div class = "col-md-7 col-md-offset-1">
          <h1><strong>Movie: </strong><%= @movie.title %></h1>
          <p><%=@movie.description %></p>
          <% if @reviews.blank? %>
            <p>No reviews yet, Be the first one to give review</p>
            <%= link_to "add review", new_movie_review_path(@movie), class: "btn btn-danger" %> 
          <% else %>
            <% @reviews.each do |review| %>
              <div class= "reviews">
                <p><%= review.rating %></p>
                <p><%= review.comment %></p>
                <%= link_to "edit_comment", edit_movie_review_path(review.movie_id,review.id) %>|
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
</div>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reviews/_form.html.erb
<%= form_with model: @movie ,mode: @review, url: movie_reviews_path, local: true  do |form| %>
  

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit() %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>
<%= form_for [@movie, @review], url: movie_review_path do |form| %>
  
  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit 'update' %>
  </div>
<% end %>
<%=link_to "delete",movie_review_path(@review.movie_id,@review.id) , :confirm => 'Are you sure?', :method => :delete %>


<%= link_to 'Show', "#" %> |
<%= link_to 'Back', movie_path(:movie_id) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', movie_reviews_path(:movie_id) %>